# Generated by Django 4.0.4 on 2022-05-13 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paided',
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Оплачен'),
        ),
    ]
